server.port=8080

# MySQL Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/interview_trainer
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# IBM Watsonx Credentials
ibm.cloud.api-key=${IBM_CLOUD_API_KEY}
ibm.watsonx.project-id=${IBM_WATSONX_PROJECT_ID}
ibm.watsonx.url=https://us-south.ml.cloud.ibm.com/ml/v1/text/generation?version=2024-05-01


